# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/www"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/typescript-config"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/firebase-config"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/voids-ap-provider"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/voids-oai-provider"
    schedule:
      interval: "daily"
